---
- name: Ensure servers are provisioned in vpc
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Launch Instance
      ec2:
        instance_type: t2.micro
        image: ami-036affea69a1101c9
        wait: yes
        group: default
        count: 1
        vpc_subnet_id: subnet-b0a397c9
        assign_public_ip: yes
        region: us-west-2
        key_name: Ansible
