---
- name: Ensure servers are provisioned in vpc
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Launch Instance
      ec2:
        instance_type: t2.micro
        image: ami-0b500ef59d8335eee
        wait: yes
        group: webserver
        count: 1
        vpc_subnet_id: subnet-523b063a
        assign_public_ip: yes
        region: us-west-2
        key_name: Ansible
