---
- name: server group are provisioned in ec2
  hosts: localhost
  gather_facts: false
  vars:
    # requires ec2_stack_name, ec2_region and ec2_key_name
    ec2_exact_count: 1

  tasks:
  - name: search for the latest centos7 ami
    ec2_ami_find:
      owner: "410186602215"
      region: "{{ ec2_region }}"
      name: "CentOS Linux 7 x86_64 HVM EBS*"
    register: find_results

  - name: exact count of stack ec2 instances running
    ec2:
      key_name: "{{ ec2_key_name }}"
      group: "{{ ec2_stack_name }}-webservers"
      volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 8
        delete_on_termination: true
      vpc_subnet_id: "{{ vpc_subnet.subnet.id }}"
      instance_type: t2.micro
      image: "{{ find_results.results[0].ami_id }}"
      wait: true
      region: "{{ ec2_region }}"
      exact_count: "{{ ec2_exact_count }}"
      count_tag:
        Count: "{{ ec2_stack_name }}"
      instance_tags:
        Name: "{{ ec2_stack_name }}"
        Count: "{{ ec2_stack_name }}"
      assign_public_ip: true
    register: ec2

  - name: display stack instances info
    debug:
      var: ec2
      verbosity: 1

  - name: all instances are ready
    wait_for:
      port: 22
      host: "{{ item.public_ip }}"
      search_regex: OpenSSH
    with_items: "{{ ec2.tagged_instances }}"

  - name: pause to let cloud init to complete
    pause:
      seconds: 90
