---
- hosts: web:haproxy
  gather_facts: yes

- hosts: web
  name: performs rolling restart
  gather_facts: no
  serial: 1
  become: yes
  vars:
    haproxy_host: "{{ groups['haproxy'] | first }}"
  
  # note: assume a single haproxy
  pre_tasks:
    - name: disable the server in haproxy
      haproxy: 
        state: disabled 
        host: "{{ inventory_hostname }}"
        backend: web_backend
      delegate_to: "{{ haproxy_host }}"

  roles:
    - apache-simple 

  post_tasks:
    - name: pause for demonstration purposes
      pause:
        seconds: 10
    - name: enable the server in haproxy
      haproxy: 
        state: enabled 
        host: "{{ inventory_hostname }}"
        backend: web_backend
      delegate_to: "{{ haproxy_host }}"

