---
- hosts: "{{ web_group }}:{{ haproxy_host }}"
  gather_facts: yes

- hosts: "{{ web_group }}"
  name: performs rolling restart
  gather_facts: no
  serial: 1
  become: yes

  # note: assume a single haproxy
  pre_tasks:
    - name: disable the server in haproxy
      haproxy: 
        state: disabled 
        host: "{{ inventory_hostname }}"
        backend: web_backend
      delegate_to: "{{ groups[haproxy_host][0] }}"

  roles:
    - 8ball-service

  post_tasks:
    - name: enable the server in haproxy
      haproxy: 
        state: enabled 
        host: "{{ inventory_hostname }}"
        backend: web_backend
      delegate_to: "{{ groups[haproxy_host][0] }}"

